WICG/observable

README.md

The `finish` method in example 5 is unused. Removing it will make the example easier to quickly grok.

Remove redundant function declaration

---

README.md

Closes #27. Per discussion there, it seems we've landed on:
- `toArray()` causing a subscription, and asynchronously yielding an array via a Promise, which seems natural
- `forEach()` per https://github.com/domfarolino/observable/issues/29#issuecomment-1656292907, this also causes a subscription, so it shouldn't return an `Observable`. And since there's no accumulated or passed-through values, it returns undefined.

Fix `forEach` and `toArray` return types

---

README.md

This PR satisfies the rest of #26. It uses more specific callback types for the following operators:
- `map()`
- `flatMap()`
- `forEach()`
In particular, it uses the [unsigned long long](https://webidl.spec.whatwg.org/#idl-unsigned-long-long) WebIDL type to represent the "index" of the item being passed into the corresponding callback, since it is the largest _integer_ type that WebIDL is. At first I was worried about that, because that type has a max value of 2<sup>64</sup> - 1, which is strictly larger than ECMAScript's "Number" type, which appears to be used for the same "index" argument in the Iterator helpers (see [`map()`](https://tc39.es/proposal-iterator-helpers/#sec-iteratorprototype.map)) and AsyncIterator helpers (see [`map()`](https://tc39.es/proposal-async-iterator-helpers/#se …

Use more specific callback types

---

README.md

This closes #11 to the best of my ability, by describing the albeit slightly-tenuous connection this proposal has to direct end user needs.
WDYT @domenic? I tried looking for an AbortController TAG review — since that's an API I think motivated by ergonomics, too, and integrates _with_ this one — and found that there was not one (maybe we weren't doing TAG reviews in the same way back then). The closest I could find was https://github.com/w3ctag/design-reviews/issues/569, which does not mention user needs at all (neither does https://github.com/whatwg/dom/issues/911 it appears).
I'm hoping this will be "good enough".

Describe user needs

---

README.md

This PR should close #28 and #44, by providing a static `Observable.from()` method, as well as changing `takeUntil()` — the only web platform method proposed here that takes "an Observable" — to accept the same kinds of objects that `Observable.from()` does.
I had some trouble initially writing this PR. For example: when used as an argument, WebIDL's `Promise<T>` type accepts native Promises as well as all thenables, I believe, which appears to be achieved by delegating to ECMAScript's laxness around thenables. As proposed in this repository, Observables are not part of the ECMAScript language, so they don't get special ES<->WebIDL conversion steps that we might be able to use to accept anything that:
- Is an `Observable`; or
- Is a `Promise<T>`; or
- Has a non-null `Symbol.iterator`; or …

`Observable.from()` & accept conversions

---

README.md

Closes #66 by introducing `ObservableEventListenerOptions`, which does NOT include `signal` or `once`. If we wish to expand this later we can, but I think starting with the simplest configuration is best initially.

Use `ObservableEventListenerOptions`

---

README.md

This closes https://github.com/WICG/observable/issues/76. This PR introduces the `subscriber.active` boolean attribute that can be used from within an Observable to determine whether a subscription is still active. I am still personally a tiny but unsure whether this is really necessary, so I'd like to use this space to describe the semantics and how it differs from other APIs, so we can come to a conclusion on this, since @benlesh feels much more strongly about this API.
On the surface it seems that `subscriber.active === !subscriber.signal.aborted`[^1], however this is not quite true. The lifecycle of an Observable is the following:
1. Active subscription
2. `subscriber.complete()/error()` is called from script
3. The subscription is no longer "active", meaning the bodies of those …

Introduce `Subscriber#active` boolean

---

README.md

This closes https://github.com/WICG/observable/issues/76. This PR introduces the `subscriber.active` boolean attribute that can be used from within an Observable to determine whether a subscription is still active. I am still personally a tiny but unsure whether this is really necessary, so I'd like to use this space to describe the semantics and how it differs from other APIs, so we can come to a conclusion on this, since @benlesh feels much more strongly about this API.
On the surface it seems that `subscriber.active === !subscriber.signal.aborted`[^1], however this is not quite true. The lifecycle of an Observable is the following:
1. Active subscription
2. `subscriber.complete()/error()` is called from script
3. The subscription is no longer "active", meaning the bodies of those …

Add `Subscriber#active` boolean (take 2)

---

README.md

Introduce `ObserverOptions` for signal to live in

---

spec.bs

This closes #71. The WebIDL Standard is now poised to support typedef unions between dictionary and callback types, which would enables a highly desired ergonomic feature: subscribing with just a callback instead of a full-blown `Observer` dictionary. See https://github.com/whatwg/webidl/pull/1353 and https://github.com/WICG/observable/issues/71#issuecomment-1804042861. The work is just waiting on another implementer besides Chromium, which we may be able to get via this proposal, which is a concrete user of this proposed Web IDL behavior.
Work is underway to update the Chromium implementation to match this as well: https://chromium-review.googlesource.com/c/chromium/src/+/5071992
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/89.html" title="Last updated on Nov 29, …

Support Observer callback union for subscription

---

spec.bs

This does not include anything teardown-related, any of the operators, or EventTarget integration.

Spec the guts of the Observable & Subscriber interfaces

---

spec.bs

The web platform tests currently assert that the behavior of this PR is implemented correctly, however I missed this as part of the abstraction work in https://github.com/WICG/observable/pull/95.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/98.html" title="Last updated on Jan 9, 2024, 1:46 AM UTC (16728bd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/98/75d46a9...16728bd.html" title="Last updated on Jan 9, 2024, 1:46 AM UTC (16728bd)">Diff</a>

Null check algorithms that get null after closing

---

spec.bs

This PR finishes spec'ing the `toArray()` operator, as a warm-up for the rest.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/97.html" title="Last updated on Jan 11, 2024, 3:13 PM UTC (48c33e5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/97/457ba36...48c33e5.html" title="Last updated on Jan 11, 2024, 3:13 PM UTC (48c33e5)">Diff</a>

Spec the `toArray()` operator

---

spec.bs

Closes #99
***
<a href="https://pr-preview.s3.amazonaws.com/keithamus/observable/pull/101.html" title="Last updated on Jan 17, 2024, 9:22 PM UTC (46743cb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/101/457ba36...keithamus:46743cb.html" title="Last updated on Jan 17, 2024, 9:22 PM UTC (46743cb)">Diff</a>

rename "Observer" to "SubscriptionObserver"

---

spec.bs

This seems like one of the more complicated operators, so hopefully the attempt here is sound.
The corner cases around this one are ensuring that we properly unsubscribe from `|notifier|` and `|sourceObservable|` simultaneously whenever we need to. This PR has a lot of documentation, so I'll direct the reader's attention to the text there which describes the mechanics I've put in place to hopefully get it all right.
WPTs incoming.
Prototype implementation in Chromium: https://chromium-review.googlesource.com/c/chromium/src/+/5228477.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/103.html" title="Last updated on Jan 23, 2024, 3:29 PM UTC (4640546)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/103/cedca3d...4640546.html" title="Last …

Spec the `Observer#takeUntil()` operator

---

spec.bs

The original version of this PR made it so if the `|mapper|` callback throws an error, it is "reported" to the global.
However, I've since fixed this to invoke the `error()` method on the relevant "Subscriber". This will either (a) [let the subscriber handle it][1], or (b) if there are no error steps, report the exception (due to the [default error steps][2]). That's the right behavior.
Additionally, in this error-case we *also* need to unsubscribe from the `|sourceObservable|`, which is accomplished by having the nexts steps abort an `AbortController` that `|signal|` is derived from, where `|signal|` is the `AbortSignal` passed into the outer Observable subscription.
Tests are in https://github.com/web-platform-tests/wpt/pull/42996/files#diff-8bcbcee0a9e290fe595f3a4d260648dc3900c67bab5925 …

Spec the `map()` operator

---

spec.bs

This CL introduces no behavior change to the `takeUntil()` operator, it only implements a simplification. Prior to this PR, `takeUntil()` declared an AbortController which managed an AbortSignal that fed into the `sourceObservable` and `notifier` Observable subscriptions. This was so that the two Observables could trigger unsubscriptions to each other, if i.e., `sourceObservable` completes, or if `notifier` next()s or errors()s.
But I didn't realize that we don't actually have to do that. As long as those operations either "complete" or "error" the "outer" `Subscriber` (that is associated with the Observable returned from `takeUntil()`), then the outer Subscriber's signal will be aborted, and we can simply use that AbortSignal as the input to the subscription of `sourceObservable` and …

Simplify `takeUntil()` unsubscription

---

spec.bs

This PR "fixes" Observable unsubscription/teardown timing. As a matter
of accidental historical precedent, Observables in JavaScript (but not
in other languages) had implemented the "rule" that upon
Subscriber#error() or Subscriber#complete(), the subscriber would:
1. First, invoke the appropriate Observer callback, if provided (i.e.,
complete() or error() callback).
2. Signal abort Subscriber#signal, which invokes any teardowns and also
fires the `abort` event at the signal.
However, after dom@chromium.org discussed this more with
ben@benlesh.com, we came to the conclusion that the principle of "as
soon as you know you will teardown, you MUST close the subscription and
any upstream subscriptions" should be followed. This means the above
steps must be inverted. This is a small-in-size but …

Fix Observable unsubscription timing

---

spec.bs

When spec'ing the `map()` operator, I was originally under the impression that if the `Mapper` callback threw an error, we would have to signal abort on an `AbortController` that manipulated the source Observable's subscriber. But upon reading the spec, I realize that simply:
> If [an exception E was thrown](https://webidl.spec.whatwg.org/#an-exception-was-thrown), then run subscriber’s [error()](https://wicg.github.io/observable/#dom-subscriber-error) method
... is plenty. That's because when we signal error on the "outer" `Subscriber`, this will abort the `AbortSignal` associated with that "outer" subscriber's AbortSignal.... and that "outer" AbortSignal is what the source Observable's subscription's signal is derived from.
***
<a …

Simplify `map()` internal observer

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/112.html" title="Last updated on Feb 21, 2024, 7:14 PM UTC (b201069)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/112/a1d9ecb...b201069.html" title="Last updated on Feb 21, 2024, 7:14 PM UTC (b201069)">Diff</a>

Spec the `filter()` operator

---

spec.bs

This operator's semantics include the behavior of not ever subscribing to the source Observable if the passed in `amount` argument is `0`. Additionally, in that case we automatically invoke `Subscriber#complete()`.
At the moment, the tests for this are in https://github.com/web-platform-tests/wpt/pull/44512, but they will be moved to https://github.com/web-platform-tests/wpt/pull/42996, and then moved to the Chromium implementation where they'll land as part of the Chromium review process.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/113.html" title="Last updated on Feb 13, 2024, 7:38 PM UTC (5f16fc8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/113/29fabd5...5f16fc8.html" title="Last updated on Feb 13, 2024, 7:38 PM UTC …

Spec the `take()` operator

---

spec.bs

CC @keithamus, if you're interested.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/117.html" title="Last updated on Feb 14, 2024, 1:50 AM UTC (ac3fd48)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/117/29fabd5...ac3fd48.html" title="Last updated on Feb 14, 2024, 1:50 AM UTC (ac3fd48)">Diff</a>

Spec the `drop()` operator

---

spec.bs

This is the same as #123
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/124.html" title="Last updated on Mar 18, 2024, 5:40 PM UTC (64690b8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/124/ec12e21...64690b8.html" title="Last updated on Mar 18, 2024, 5:40 PM UTC (64690b8)">Diff</a>

Spec the `flatMap` operator (attempt 2)

---

spec.bs

This PR spec's the `switchMap()` operator.
This PR closes https://github.com/WICG/observable/issues/52 and makes progress on https://github.com/WICG/observable/issues/126.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/130.html" title="Last updated on Apr 23, 2024, 3:40 PM UTC (c4db0e1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/130/e3e8f94...c4db0e1.html" title="Last updated on Apr 23, 2024, 3:40 PM UTC (c4db0e1)">Diff</a>

Spec the `switchMap` operator

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/137.html" title="Last updated on Apr 23, 2024, 7:23 PM UTC (d609f27)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/137/b4b9d43...d609f27.html" title="Last updated on Apr 23, 2024, 7:23 PM UTC (d609f27)">Diff</a>

Spec `some()`, `every()`, and `find()` operators

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/133.html" title="Last updated on Apr 10, 2024, 9:07 PM UTC (063e326)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/133/e3e8f94...063e326.html" title="Last updated on Apr 10, 2024, 9:07 PM UTC (063e326)">Diff</a>

Spec the `last()` operator

---

spec.bs

Reverts WICG/observable#133. It was landed prematurely. See https://github.com/WICG/observable/pull/131#issuecomment-2083248807 among other discussion.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/143.html" title="Last updated on May 4, 2024, 6:47 PM UTC (92bbb3d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/143/e6ee22b...92bbb3d.html" title="Last updated on May 4, 2024, 6:47 PM UTC (92bbb3d)">Diff</a>

Revert "Spec the `last()` operator"

---

spec.bs

Closes https://github.com/WICG/observable/issues/65 and makes progress on https://github.com/WICG/observable/issues/126.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/131.html" title="Last updated on May 5, 2024, 2:42 PM UTC (501b4f7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/131/e3e8f94...501b4f7.html" title="Last updated on May 5, 2024, 2:42 PM UTC (501b4f7)">Diff</a>

Spec the `first()` operator

---

spec.bs

This is a reland of #133. At the moment, the inconsistencies with `find()` that disqualify it for landing right now have not been addressed, but they will be soon.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/144.html" title="Last updated on May 5, 2024, 2:47 PM UTC (ad90abe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/144/7a4c941...ad90abe.html" title="Last updated on May 5, 2024, 2:47 PM UTC (ad90abe)">Diff</a>

Reland: Spec the `last()` operator

---

spec.bs

Fix https://github.com/WICG/observable/issues/114
***
<a href="https://pr-preview.s3.amazonaws.com/tetsuharuohzeki/observable/pull/129.html" title="Last updated on Jun 27, 2024, 8:21 PM UTC (9f8040d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/129/98a4f07...tetsuharuohzeki:9f8040d.html" title="Last updated on Jun 27, 2024, 8:21 PM UTC (9f8040d)">Diff</a>

Add the step to check subscriber's active state to next(value)/error(error)/complete() as a shortcut

---

spec.bs

As spec-ed the behaviour of take/drop means this prints the values only once:
```js
const obs = Observable.from([1,2,3,4,5,6]);
const firstThree = obs.take(3);
firstThree.forEach((v) => {
console.log(v);
});
// This doesn't print anything
firstThree.forEach((v) => {
console.log(v);
});
```
The intended behaviour I would expect is that each subscription has it's own counter.
The fix provided here just makes a new variable local to each subscription rather than re-using the argument to take/drop.
***
<a href="https://pr-preview.s3.amazonaws.com/Jamesernator/observable/pull/155.html" title="Last updated on Jul 11, 2024, 4:53 AM UTC (0316480)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/155/7b4cb07...Jamesernator:0316480.html" title="Last updated on Jul 11, …

Make take/drop not share state across subscriptions

---

spec.bs

Before this pull request, a `Subscriber`'s internal signal — the one exposed by [`Subscriber#signal()`][1] — was a [dependent signal][3] based on two input signals:
1. The [SubscribeOptions#signal][2], if non-null; and
2. The Subscriber's internal AbortController's (named `complete or error controller` before this CL) AbortSignal.
Then, whenever the internal _dependent_ signal is aborted, we run the **abort algorithm** which (**a**) "closes" the subscription (sets `subscriber.active` to false), and (**b**) executes all teardowns.
But (**1**) the use of _dependent_ AbortSignals (i.e., making each Subscriber's signal dependent on its downstream Subscriber's signal), and (**2**) tying a Subscriber's teardown execution to its internal signal's abort algorithms, introduced inconsistent …

Don't use dependent abort signals inside `Subscriber`

---

spec.bs

@maraisr and I have renamed `SubscriptionObserverCallback` to `ObservableSubscriptionCallback` based on [review feedback from @rreno here](https://github.com/WebKit/WebKit/pull/23067#pullrequestreview-2178848864)
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/157.html" title="Last updated on Jul 22, 2024, 7:57 AM UTC (54aa7ac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/157/f954c91...54aa7ac.html" title="Last updated on Jul 22, 2024, 7:57 AM UTC (54aa7ac)">Diff</a>

Rename `SubscriptionObserverCallback` to `ObservableSubscriptionCallback`

---

spec.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/164.html" title="Last updated on Jul 26, 2024, 7:08 PM UTC (775f93b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/164/1b470a5...775f93b.html" title="Last updated on Jul 26, 2024, 7:08 PM UTC (775f93b)">Diff</a>

Fix indentation in first and last algos

---

spec.bs

These steps are numbered incorrectly due to wonky indentation. This fixes the steps so they're indented correctly.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/162.html" title="Last updated on Jul 26, 2024, 1:05 PM UTC (cc5852c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/162/1b470a5...cc5852c.html" title="Last updated on Jul 26, 2024, 1:05 PM UTC (cc5852c)">Diff</a>

fix indentation in "subscribe to an" algo

---

spec.bs

Am currently implementing `forEach` in WebKit, and noticed we had some [inconsistencies](https://github.com/WebKit/WebKit/blob/d128fcbc4cf949b84f671691d19297f0fda88349/Source/WebCore/dom/MapperCallback.idl#L26) with what we call the value we pass these callbacks. Lets tidy this up in the spec.
cc @keithamus
***
<a href="https://pr-preview.s3.amazonaws.com/maraisr/observable/pull/167.html" title="Last updated on Aug 2, 2024, 3:41 AM UTC (ec10807)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/167/530d498...maraisr:ec10807.html" title="Last updated on Aug 2, 2024, 3:41 AM UTC (ec10807)">Diff</a>

Let the `value` argument be consistent

---

README.md
spec.bs

See https://github.com/WICG/observable/issues/39 for discussion, and https://chromium-review.googlesource.com/c/chromium/src/+/5730072 for WPTs that will be upstreamed shortly.
Closes #39.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/161.html" title="Last updated on Aug 13, 2024, 10:38 AM UTC (6f33850)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/161/f954c91...6f33850.html" title="Last updated on Aug 13, 2024, 10:38 AM UTC (6f33850)">Diff</a>

Rename `EventTarget#on()` to `EventTarget#when()`

---

README.md

This can close https://github.com/WICG/observable/issues/93 which ultimately doesn't need to be open. It's just as easy (and less cluttered from an issues management perspective) to just have this content in the README.

Add standards issues links

---

spec.bs

Fixes #165. 
This seems to marry up with [Chrome's impl](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/subscriber.cc;l=64-72;drc=105770df485ace262780d95126bb60b1a16ec340;bpv=0;bpt=1):
```c++
if (downstream_signal->aborted()) {
CloseSubscription(
script_state,
/*abort_reason=*/downstream_signal->reason(script_state));
} else {
close_subscription_algorithm_handle_ = downstream_signal->AddAlgorithm(
MakeGarbageCollected<CloseSubscriptionAlgorithm>(
this, downstream_signal, script_state));
}
```
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/166.html" title="Last updated on Aug 13, 2024, 5:08 PM UTC (7905c52)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/166/530d498...7905c52.html" title="Last …

Pass abortsignal reason to close a subscription

---

spec.bs

Closes https://github.com/WICG/observable/issues/111.
See https://chromium-review.googlesource.com/c/chromium/src/+/5435614 for tests that have been upstreamed to the WPT repository.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/168.html" title="Last updated on Aug 22, 2024, 5:18 PM UTC (eae66ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/168/34820c9...eae66ae.html" title="Last updated on Aug 22, 2024, 5:18 PM UTC (eae66ae)">Diff</a>

Spec `inspect()` operator

---

spec.bs

Tests are being upstreamed in https://chromium-review.googlesource.com/c/chromium/src/+/5823731.
Closes #64.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/172.html" title="Last updated on Aug 28, 2024, 4:07 PM UTC (761aee1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/172/69ad0de...761aee1.html" title="Last updated on Aug 28, 2024, 4:07 PM UTC (761aee1)">Diff</a>

Spec the `catch()` operator

---

spec.bs

This specs the `reduce()` operator discussed in https://github.com/WICG/observable/issues/126. Tests will be upstreamed in https://chromium-review.googlesource.com/c/chromium/src/+/5817639. That should leave only `catch()` and `finally()` operators left.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/171.html" title="Last updated on Aug 28, 2024, 2:19 AM UTC (2760e00)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/171/69ad0de...2760e00.html" title="Last updated on Aug 28, 2024, 2:19 AM UTC (2760e00)">Diff</a>

Spec the `reduce()` operator

---

README.md

Correct a spelling mistake in README.md

---

spec.bs

This fixes #174 to make the spec match the implementation, which is what the web platform tests expect. The proposal to use TC39's explicit resource management proposal will be considered in https://github.com/WICG/observable/issues/150 as a follow-up.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/176.html" title="Last updated on Sep 21, 2024, 10:29 PM UTC (b541906)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/176/6271d57...b541906.html" title="Last updated on Sep 21, 2024, 10:29 PM UTC (b541906)">Diff</a>

Fix `inspect()` error and complete callbacks

---

spec.bs

Reading the [Chrome Implementation](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/observable.cc;l=577-581?q=Observables%20foreach&ss=chromium) of `.first`, and the associated [wpt tests](https://github.com/web-platform-tests/wpt/blob/3585305e8365779fac42dd87e4f52c89c3e884a6/dom/observable/tentative/observable-first.any.js#L38-L54) I think it is valuable in having the spec reflective of this.
***
<a href="https://pr-preview.s3.amazonaws.com/maraisr/observable/pull/179.html" title="Last updated on Oct 20, 2024, 11:29 AM UTC (f77730e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/179/a56ef28...maraisr:f77730e.html" title="Last updated on Oct 20, 2024, 11:29 AM UTC (f77730e)">Diff</a>

Update spec to mention rejecting with a new RangeError

---

README.md

In the websocket example the return value of the subscribe calls are stored in variables.
The current spec doesn't implement a "subscription" return value, this might be a left over from the past.
Fixes #184

Correct example in README.md

---

spec.bs

I think there is a possible event listener leak that can occur if we don't have a mechanism to clean up event listeners as subscriptions are aborted.
In WebKit I confirmed, that if we were to follow the spec we'd keep listeners around for a little too long:
Much [like Chrome's EventTarget implementation](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/events/event_target.cc;l=362-366), WebKits' also immediately take ownership of the EventListener, so that despite the Observable is marked for GC (`active == 0`), the listener hangs around.
and I think Chrome had a similar discovery, as they [also forward the signal](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/events/event_target.cc;l=271;drc=616d60f …

We should forward the subscribers abort signal to eventListeners

---

spec.bs

This makes a lot of progress towards #159 by specifying the semantics of `from()`, while also then using that algorithm in `takeUntil()`.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/160.html" title="Last updated on Jan 25, 2025, 5:48 AM UTC (57b2d19)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/160/35be035...57b2d19.html" title="Last updated on Jan 25, 2025, 5:48 AM UTC (57b2d19)">Diff</a>

Spec `from()` static converter

---

spec.bs

This PR fixes `Observable.from()`'s synchronous iteration to respond to aborted signals properly, and close the iterator accordingly. Upon subscription, this PR adds checks to see whether the subscriber's signal is aborted:
1. The first is initially upon subscription. Consistent with [Chromium implementation](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/observable.cc;l=1946-1948;drc=4b00956a8d971cf5ec8ec45a105b5dd8802d4a42) and [tests](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/external/wpt/dom/observable/tentative/observable-from.any.js;l=1437-1464;drc=4b00956a8d971cf5ec8ec45a105b5dd8802d4a42) (tests are being modified [here](https://chromium-review.googlesource.com/c/chromium/src/+/6202182)).
2. …

`from()`: Close synchronous iterators properly

---

spec.bs

This PR closes https://github.com/WICG/observable/issues/191 by spec'ing async iterable support. Along with support for general iteration over async iterables, we support consulting the Subscriber's signal to discontinue the iteration at three points:
1. Immediately on subscription, so that we don't even pull out the iterator from the iterable. This matches the [Chromium implementation](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/observable.cc;l=1600-1602;drc=4b00956a8d971cf5ec8ec45a105b5dd8802d4a42) and [tests](https://chromium-review.googlesource.com/c/chromium/src/+/6202182).
2. After we obtain the iterator, the act of which may abort the signal. This also matches the [Chromium implementation](https://chromium-review.googlesource.com/c/ch …

`from()`: Support async iterable conversion

---

spec.bs

Closes #170. Closes #178.
Corresponding Chromium change _and_ tests: https://chromium-review.googlesource.com/c/chromium/src/+/6221901.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/197.html" title="Last updated on Feb 21, 2025, 2:09 AM UTC (a819eeb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/197/df571e8...a819eeb.html" title="Last updated on Feb 21, 2025, 2:09 AM UTC (a819eeb)">Diff</a>

Spec ref-counted producers

---

spec.bs

This PR specs the `finally()` operator, registering the callback to its internal Subscriber's teardown list.
~Mirroring the `finally` keyword, its semantics are such that on both producer-initiated and consumer-initiated unsubscription, the finally operator's callback runs. The only remaining open question about this operator has to do with subtle timing between the finally() operator and source Observable teardown execution. See https://github.com/WICG/observable/issues/151 for discussion there. I don't think that needs to block this PR, but it does need to resolve one way or another.~
The above issues are struckthrough and obsolete; see https://github.com/WICG/observable/issues/151#issuecomment-2675072493.
Tests are being landed in …

Spec the `finally()` operator

---

spec.bs

Thanks to @jakearchibald for catching this and reporting it. This text must've existed in the spec PR at one point, since I've [quoted the spec text above the implementation](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/observable.cc;l=1950-1954;drc=5f81609f7c343a17175b71d07ae02d6f5d09675f). I'm pretty sure what happened is when I did a ton of rebasing for the async stuff to finish it off in parallel with the ref-counted producer change, the later changes were lost, and here we are.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/observable/pull/202.html" title="Last updated on Feb 27, 2025, 5:24 PM UTC (bc22e18)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/observable/202/5e4a6a5...bc22e18.html" title="Last updated …

Call Subscriber's next method for async iterators
